### ISSUE TITLE
Modernize Modelforge CI

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/modelforge#38]
- [ ] Build and push the PyPi package on tags (working example: https://github.com/src-d/minhashcuda/blob/master/.travis.yml#L15)
- [ ] Use flake8 as in sourced-ml

**Comment by vmarkovtsev** [comment]
@smola How do we upload the autogenerated documentation for this project?

**Comment by smola** [comment]
@vmarkovtsev  `/docs` should be for gitbook (see [gitbase](https://github.com/src-d/gitbase)) as example.
For autogenerated docs, at the moment we have `docsrv` to generate and serve them (see [engine example](https://engine.sourced.tech/v0.6.4/api/python/)).

**Comment by vmarkovtsev** [comment]
@smola What are our exact steps to serve the autogenerated Modelforge docs at sourced.tech?

**Comment by vmarkovtsev** [comment]
As discussed with @smola docs are postponed until https://github.com/src-d/feature-idea/issues/59
