### ISSUE TITLE
Test Python 3.7 in Travis

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/modelforge#46]
Example: https://github.com/src-d/style-analyzer/blob/master/.travis.yml

We should not not drop 3.4 here.

**Comment by vmarkovtsev** [comment]
@warenlg pls link to the PRs here

**Comment by warenlg** [comment]
PR https://github.com/src-d/modelforge/pull/47

**Comment by vmarkovtsev** [comment]
Modelforge is tested.

**Comment by zurk** [comment]
also this issue for sourced.ml https://github.com/src-d/ml/issues/286
