### ISSUE TITLE
Errors in the mode's description

### ISSUE THREAD

**Issue by warenlg** [src-d/modelforge#78]
When running style-analyzer's tests with modelforge 0.11.0, I met some errors dur to the model's description, like:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/lookout/style/typos/tests/test_ranking.py", line 69, in test_save_load
    print(ranker)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/modelforge/model.py", line 274, in __str__
    " ".join("%s==%s" % tuple(p) for p in self.environment["packages"])
TypeError: 'NoneType' object is not subscriptable
```
and 
```Traceback (most recent call last):
  File "lookout/style/format/tests/test_analyzer.py", line 151, in test_train_cutoff_labels
    self.assertIn("javascript", model1, str(model1))
  File "/home/waren/.local/lib/python3.6/site-packages/modelforge/model.py", line 270, in __str__
    meta["created_at"] = format_datetime(meta["created_at"])
  File "/home/waren/.local/lib/python3.6/site-packages/modelforge/meta.py", line 68, in format_datetime
    return dt.strftime("%Y-%m-%d %H:%M:%S%z")
AttributeError: 'NoneType' object has no attribute 'strftime'
```

**Comment by vmarkovtsev** [comment]
`created_at` and `environment` must always exist. Most likely the involved model files need to be updated.

**Comment by warenlg** [comment]
They exist but their value are initialize to `None` https://github.com/src-d/modelforge/blob/master/modelforge/meta.py#L33, the correct values are assigned only when we save the model somewhere. cf `_wrtite_tree`
And, for example, in `tests_analyzer.py` we just initialize a `FormatModel` https://github.com/src-d/style-analyzer/blob/master/lookout/style/format/analyzer.py#L233 then tests the model's description and it breaks with the `None` values.
Can't we initialize the models with other values like `"created_at": get_datetime_now()` for example ?

**Comment by zurk** [comment]
@vmarkovtsev 
that is true, we cannot convert `str(model)` because we miss `meta["created_at"]` when we have just created the model.

So we can just change `__str__()` method if you do not like Waren's solution.

**Comment by vmarkovtsev** [comment]
So the proper fix is to initialize `created_at` to `datetime.UtcNow()` and `environment` to `{"packages": [], "python": from collect_env_info, "platform": from collect_env_info}` in `generate_new_meta()`. I will engineer this ASAP.

**Comment by vmarkovtsev** [comment]
@zurk So once the new package is published, we need to update downstream: lookout-sdk-ml and sourced-ml
